
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Github, 
  Calendar, 
  Mail,
  FileText,
  BarChart3,
  ArrowRight,
  CheckCircle,
  Zap,
  Shield,
  Users,
  Clock,
  Bot,
  Sparkles,
  Star,
  TrendingUp,
  Globe,
  Smartphone,
  Lock,
  Rocket
} from "lucide-react";
import { Link } from "wouter";
import { motion, useScroll, useTransform } from "framer-motion";
import { useAuth } from "@/contexts/AuthContext";
import autoBriefLogo from "@/assets/autobrief-logo.png";

const Landing = () => {
  const [isDarkMode, setIsDarkMode] = useState(false);

  const toggleTheme = () => {
    setIsDarkMode(!isDarkMode);
    document.documentElement.classList.toggle('dark');
  };

  const features = [
    {
      icon: Bot,
      title: "AI-Powered Summaries",
      description: "Get intelligent daily briefs generated by advanced AI that understands your work patterns."
    },
    {
      icon: Zap,
      title: "Automated Daily Reports",
      description: "Receive comprehensive summaries every evening without lifting a finger."
    },
    {
      icon: Users,
      title: "Team Collaboration",
      description: "Keep your remote team in sync with shared insights and progress updates."
    },
    {
      icon: Shield,
      title: "Secure Integrations",
      description: "Connect your tools safely with enterprise-grade security and encryption."
    }
  ];

  const integrations = [
    { name: "GitHub", icon: Github, color: "bg-gray-900" },
    { name: "Slack", icon: Mail, color: "bg-purple-600" },
    { name: "Google Calendar", icon: Calendar, color: "bg-blue-600" },
    { name: "Jira", icon: FileText, color: "bg-blue-500" },
    { name: "Notion", icon: FileText, color: "bg-black" },
  ];

  const steps = [
    {
      step: "01",
      title: "Connect Your Tools",
      description: "Link your favorite productivity tools like GitHub, Slack, Jira, and more with secure OAuth authentication."
    },
    {
      step: "02", 
      title: "AI Analyzes Your Work",
      description: "Our AI processes your daily activities, commits, meetings, and tasks to understand your productivity patterns."
    },
    {
      step: "03",
      title: "Receive Daily Summaries",
      description: "Get beautiful, personalized summaries delivered to your inbox every evening with insights and next steps."
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 dark:from-slate-900 dark:via-slate-800 dark:to-slate-900">
      {/* Header */}
      <header className="container mx-auto px-6 py-4">
        <nav className="flex items-center justify-between">
          <Link to="/">
            <img 
              src={autoBriefLogo} 
              alt="AutoBrief" 
              className="h-28 w-48 object-contain cursor-pointer hover:opacity-80 transition-opacity"
            />
          </Link>
          <div className="flex items-center gap-6">
            <Link to="/privacy" className="text-muted-foreground hover:text-foreground transition-colors">
              Privacy Policy
            </Link>
            <Link to="/terms" className="text-muted-foreground hover:text-foreground transition-colors">
              Terms & Conditions
            </Link>
            <Link to="/contact" className="text-muted-foreground hover:text-foreground transition-colors">
              Contact Us
            </Link>
            <Link to="/auth/login">
              <Button variant="ghost" className="text-foreground">
                Sign In
              </Button>
            </Link>
            <Link to="/auth/signup">
              <Button className="gradient-primary text-white">
                Get Started
              </Button>
            </Link>
          </div>
        </nav>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-6 py-16 text-center">
        <div className="animate-fade-in">
          <Badge className="mb-6 bg-purple-100 text-purple-700 hover:bg-purple-100">
            <Sparkles className="h-3 w-3 mr-1" />
            AI-Powered Work Intelligence
          </Badge>
          <h1 className="text-5xl md:text-7xl font-bold mb-6 bg-gradient-to-r from-purple-600 via-blue-600 to-indigo-600 bg-clip-text text-transparent leading-tight">
            Never Miss a Beat<br />
            <span className="text-foreground">in Your Remote Work</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-8 leading-relaxed">
            AutoBrief AI automatically generates intelligent daily summaries of your work across GitHub, Slack, Jira, Notion, and Google Calendar. Keep your team in sync with AI-powered insights delivered to your inbox every evening.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link to="/auth/signup">
              <Button size="lg" className="gradient-primary text-white px-8 hover-scale">
                Start Free Trial
                <ArrowRight className="h-5 w-5 ml-2" />
              </Button>
            </Link>
            <Button size="lg" variant="outline" className="px-8">
              Watch Demo
            </Button>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-6 py-16">
        <div className="text-center mb-16 animate-fade-in">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Why Teams Love AutoBrief AI
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Streamline your remote work with intelligent automation that saves time and improves team communication.
          </p>
        </div>
        
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <Card key={feature.title} className="hover-scale transition-all duration-300 hover:shadow-lg animate-fade-in" style={{ animationDelay: `${index * 100}ms` }}>
              <CardContent className="p-6 text-center">
                <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-blue-500 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <feature.icon className="h-6 w-6 text-white" />
                </div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-muted-foreground text-sm">{feature.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* How It Works Section */}
      <section id="how-it-works" className="bg-muted/30 py-16">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16 animate-fade-in">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              How AutoBrief Works
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Get started in minutes with our simple three-step process.
            </p>
          </div>

          <div className="grid lg:grid-cols-3 gap-8 lg:gap-12">
            {steps.map((step, index) => (
              <div key={step.step} className="text-center animate-fade-in" style={{ animationDelay: `${index * 200}ms` }}>
                <div className="w-16 h-16 bg-gradient-to-r from-purple-500 to-blue-500 rounded-full flex items-center justify-center mx-auto mb-6 text-white text-xl font-bold">
                  {step.step}
                </div>
                <h3 className="text-xl font-semibold mb-4">{step.title}</h3>
                <p className="text-muted-foreground leading-relaxed">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Integrations Section */}
      <section className="container mx-auto px-6 py-16">
        <div className="text-center mb-16 animate-fade-in">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Connect Your Favorite Tools
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            AutoBrief integrates seamlessly with the tools you already use.
          </p>
        </div>

        <div className="flex flex-wrap justify-center items-center gap-8">
          {integrations.map((integration, index) => (
            <div 
              key={integration.name}
              className="flex items-center gap-3 p-4 rounded-lg border hover:shadow-sm transition-all duration-300 hover-scale animate-fade-in"
              style={{ animationDelay: `${index * 100}ms` }}
            >
              <div className={`w-10 h-10 rounded-lg ${integration.color} flex items-center justify-center`}>
                <integration.icon className="h-5 w-5 text-white" />
              </div>
              <span className="font-medium">{integration.name}</span>
            </div>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-gradient-to-r from-purple-500 to-blue-600 text-white py-16">
        <div className="container mx-auto px-6 text-center animate-fade-in">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Ready to Transform Your Remote Work?
          </h2>
          <p className="text-purple-100 text-xl mb-8 max-w-2xl mx-auto">
            Join thousands of remote teams who trust AutoBrief to keep them connected and productive.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <Link to="/auth/signup">
              <Button size="lg" variant="secondary" className="bg-white text-purple-600 hover:bg-gray-100 px-8">
                Start Free Trial
                <ArrowRight className="h-5 w-5 ml-2" />
              </Button>
            </Link>
            <Button size="lg" variant="outline" className="border-white text-white hover:bg-white hover:text-purple-600 px-8">
              Schedule Demo
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-background border-t py-12">
        <div className="container mx-auto px-6">
          <div className="grid md:grid-cols-4 gap-8">
            <div>
              <div className="mb-4">
                <Link to="/">
                  <img 
                    src={autoBriefLogo} 
                    alt="AutoBrief" 
                    className="h-28 w-48 object-contain cursor-pointer hover:opacity-80 transition-opacity"
                  />
                </Link>
              </div>
              <p className="text-muted-foreground text-sm">
                AI-powered work summaries for remote teams.
              </p>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Product</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><a href="#how-it-works" className="hover:text-foreground transition-colors">How it Works</a></li>
                <li><Link to="/dashboard" className="hover:text-foreground transition-colors">Dashboard</Link></li>
                <li><a href="#" className="hover:text-foreground transition-colors">Pricing</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Company</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><a href="#" className="hover:text-foreground transition-colors">About</a></li>
                <li><a href="#" className="hover:text-foreground transition-colors">Blog</a></li>
                <li><Link to="/contact" className="hover:text-foreground transition-colors">Contact</Link></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Legal</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li><Link to="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link></li>
                <li><Link to="/terms" className="hover:text-foreground transition-colors">Terms & Conditions</Link></li>
              </ul>
            </div>
          </div>
          <div className="border-t mt-8 pt-8 text-center text-sm text-muted-foreground">
            <p>&copy; 2025 AutoBrief. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
